@serverUrl = http://localhost:3000

###
GET {{serverUrl}}
###

GET {{serverUrl}}/users/get-private-room?userIds=1
Content-Type: application/json

###

POST {{serverUrl}}/auth/login
Content-Type: application/json

{
  "login": "vinhngo",
  "password": "vinhngo1999"
}

###

GET {{serverUrl}}/users/find-all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZGMwMzYxY2ZmMjZmZTg2YjM5OWE5ZCIsImxvZ2luIjoidmluaG5nbyIsImVtYWlsIjoidmluaHRydW5nbmdvQHlhaG9vLmNvbSIsImFjdGl2ZSI6dHJ1ZSwiY3JlYXRlZF9hdCI6IjIwMjQtMDktMDdUMDc6NDA6MTcuOTcxWiIsImlhdCI6MTcyNjMxNjEzNywiZXhwIjoxNzI2MzE2MTk3fQ.4-jhns5_nUxvm8HSmYHlqFEdF2v4l5UtHQKvByoqUCw

###

GET http://localhost:5001/api/message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhjNGYwODkyYjI3YjdlZTA2YzFiN2YiLCJpYXQiOjE2NzE5NDAxMjUsImV4cCI6MTY3MjAyNjUyNX0.WSgHayf2X66DM4u2AZtf5saiifvfjW7Qx_f8bwfxATA
###