apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nest-api.fullname" . }}
  labels:
    {{- include "nest-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nest-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nest-api.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ .Values.env.dbHost }}
            - name: DB_PORT
              value: "{{ .Values.env.dbPort }}"
            - name: DB_USER
              value: {{ .Values.env.dbUser }}
            - name: DB_PASS
              value: {{ .Values.env.dbPass }}
            - name: DB_DATABASE
              value: {{ .Values.env.database }}
            - name: NODE_ENV
              value: {{ .Values.env.nodeEnv }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
