@serverUrl = https://mern-v-chat-server.onrender.com
@localUrl = http://localhost:3003

###

POST {{localUrl}}/users/register
Content-Type: application/json

{
  "login": "vinhngo",
  "email": "vinhtrungngo@yahoo.com",
  "password": "vinhngo1999",
  "passwordRepeat": "vinhngo1999"
}

###

POST {{localUrl}}/users/login
Content-Type: application/json

{
  "login": "vinhngo",
  "password": "vinhngo1999"
}

###

GET {{localUrl}}/users/find-all
Content-Type: application/json

###
GET {{localUrl}}/users/find-one/66dc0361cff26fe86b399a9d
Content-Type:  application/json
###

PATCH http://localhost:5002/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhjNGYwODkyYjI3YjdlZTA2YzFiN2YiLCJpYXQiOjE2NzE5NDAxMjUsImV4cCI6MTY3MjAyNjUyNX0.WSgHayf2X66DM4u2AZtf5saiifvfjW7Qx_f8bwfxATA

{
  "title": "React",
  "description": "React",
  "url": "react.com",
  "status": "TO LEARN"
}
###

GET http://localhost:5001/api/user/search?page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhjNGYwODkyYjI3YjdlZTA2YzFiN2YiLCJpYXQiOjE2NzE5NDAxMjUsImV4cCI6MTY3MjAyNjUyNX0.WSgHayf2X66DM4u2AZtf5saiifvfjW7Qx_f8bwfxATA
###

GET http://localhost:5001/api/message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhjNGYwODkyYjI3YjdlZTA2YzFiN2YiLCJpYXQiOjE2NzE5NDAxMjUsImV4cCI6MTY3MjAyNjUyNX0.WSgHayf2X66DM4u2AZtf5saiifvfjW7Qx_f8bwfxATA
###

POST http://localhost:5001/api/message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhjNGYwODkyYjI3YjdlZTA2YzFiN2YiLCJpYXQiOjE2NzE5NDAxMjUsImV4cCI6MTY3MjAyNjUyNX0.WSgHayf2X66DM4u2AZtf5saiifvfjW7Qx_f8bwfxATA
Content-type: application/json

{
  "recipient":"638c4f0892b27b7ee06c1b7f",
  "sender":"63a47219e7a065472ffdbd9a",
  "text":"new mess"
}
###

PUT http://localhost:5000/api/message/6061c25ac2533d41dcae2b19
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhjNGYwODkyYjI3YjdlZTA2YzFiN2YiLCJpYXQiOjE2NzE5NDAxMjUsImV4cCI6MTY3MjAyNjUyNX0.WSgHayf2X66DM4u2AZtf5saiifvfjW7Qx_f8bwfxATA

{
  "title": "Vue",
  "description": "VUEEEEE",
  "url": "https://vuejs.org",
  "status": "LEARNING"
}

###

DELETE http://localhost:5001/api/conversation/63a47219e7a065472ffdbd9a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhjNGYwODkyYjI3YjdlZTA2YzFiN2YiLCJpYXQiOjE2NzE5NDAxMjUsImV4cCI6MTY3MjAyNjUyNX0.WSgHayf2X66DM4u2AZtf5saiifvfjW7Qx_f8bwfxATA
Content-type: application/json

###

GET http://localhost:5001/api/conversation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhjNGYwODkyYjI3YjdlZTA2YzFiN2YiLCJpYXQiOjE2NzE5NDAxMjUsImV4cCI6MTY3MjAyNjUyNX0.WSgHayf2X66DM4u2AZtf5saiifvfjW7Qx_f8bwfxATA
###

GET http://localhost:5001/error
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhjNGYwODkyYjI3YjdlZTA2YzFiN2YiLCJpYXQiOjE2NzE5NDAxMjUsImV4cCI6MTY3MjAyNjUyNX0.WSgHayf2X66DM4u2AZtf5saiifvfjW7Qx_f8bwfxATA
###

GET http://localhost:5001/api/message/63a47219e7a065472ffdbd9a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhjNGYwODkyYjI3YjdlZTA2YzFiN2YiLCJpYXQiOjE2NzIxNTUxNjksImV4cCI6MTY3MjI0MTU2OX0.DIVq6Jej-wvQjD5Gcyol5X0pTAYakfREy4d_DEW7sbQ